name: Build and Deploy Back on Azure App Service

on:
  push:
    branches:
      - 'master'

env:
  AZURE_WEBAPP_NAME: back-aurora-{{ nanoid }}

jobs:
  tests:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Create .env file
      run: |
        touch .env
        echo "$DOT_ENV" > .env
      shell: bash
      env:
        DOT_ENV: ${{secrets.DOT_ENV}}
    - name: Unit testing
      run: npm run test
    - name: Acceptance testing
      run: npm run test:e2e

  deploy:
    name: GCP App Engine Deploy
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          touch .env
          echo "$DOT_ENV" > .env
        shell: bash
        env:
          DOT_ENV: ${{secrets.DOT_ENV}}
      - name: Build project
        run: npm run build
      - name: Run Azure webapp deploy action using publish profile credential
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}