runtime: nodejs16
service: back-aurora-{{ nanoid }}
env: standard
entrypoint: npm run start:prod
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 2
  min_idle_instances: 1
  max_idle_instances: automatic